export const AIRPORTS = [
  // ── US Large Hubs ──────────────────────────────────────────────────────────
  { code: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", state: "GA", country: "US" },
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles", state: "CA", country: "US" },
  { code: "ORD", name: "O'Hare International", city: "Chicago", state: "IL", country: "US" },
  { code: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", state: "TX", country: "US" },
  { code: "DEN", name: "Denver International", city: "Denver", state: "CO", country: "US" },
  { code: "JFK", name: "John F. Kennedy International", city: "New York", state: "NY", country: "US" },
  { code: "SFO", name: "San Francisco International", city: "San Francisco", state: "CA", country: "US" },
  { code: "SEA", name: "Seattle-Tacoma International", city: "Seattle", state: "WA", country: "US" },
  { code: "LAS", name: "Harry Reid International", city: "Las Vegas", state: "NV", country: "US" },
  { code: "MCO", name: "Orlando International", city: "Orlando", state: "FL", country: "US" },
  { code: "MIA", name: "Miami International", city: "Miami", state: "FL", country: "US" },
  { code: "CLT", name: "Charlotte Douglas International", city: "Charlotte", state: "NC", country: "US" },
  { code: "EWR", name: "Newark Liberty International", city: "Newark", state: "NJ", country: "US" },
  { code: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix", state: "AZ", country: "US" },
  { code: "IAH", name: "George Bush Intercontinental", city: "Houston", state: "TX", country: "US" },
  { code: "BOS", name: "Logan International", city: "Boston", state: "MA", country: "US" },
  { code: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis", state: "MN", country: "US" },
  { code: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", state: "MI", country: "US" },
  { code: "PHL", name: "Philadelphia International", city: "Philadelphia", state: "PA", country: "US" },
  { code: "LGA", name: "LaGuardia Airport", city: "New York LaGuardia", state: "NY", country: "US" },
  { code: "BWI", name: "Baltimore/Washington International", city: "Baltimore", state: "MD", country: "US" },
  { code: "DCA", name: "Ronald Reagan Washington National", city: "Washington DC", state: "VA", country: "US" },
  { code: "IAD", name: "Dulles International", city: "Washington Dulles", state: "VA", country: "US" },
  { code: "MDW", name: "Chicago Midway International", city: "Chicago Midway", state: "IL", country: "US" },
  { code: "SLC", name: "Salt Lake City International", city: "Salt Lake City", state: "UT", country: "US" },
  { code: "TPA", name: "Tampa International", city: "Tampa", state: "FL", country: "US" },
  { code: "SAN", name: "San Diego International", city: "San Diego", state: "CA", country: "US" },
  { code: "PDX", name: "Portland International", city: "Portland", state: "OR", country: "US" },
  { code: "AUS", name: "Austin-Bergstrom International", city: "Austin", state: "TX", country: "US" },
  { code: "STL", name: "St. Louis Lambert International", city: "St. Louis", state: "MO", country: "US" },
  { code: "BNA", name: "Nashville International", city: "Nashville", state: "TN", country: "US" },
  { code: "RDU", name: "Raleigh-Durham International", city: "Raleigh-Durham", state: "NC", country: "US" },
  { code: "MCI", name: "Kansas City International", city: "Kansas City", state: "MO", country: "US" },
  { code: "HOU", name: "William P. Hobby Airport", city: "Houston Hobby", state: "TX", country: "US" },
  { code: "OAK", name: "Oakland International", city: "Oakland", state: "CA", country: "US" },
  { code: "SJC", name: "Norman Y. Mineta San Jose International", city: "San Jose", state: "CA", country: "US" },
  { code: "SMF", name: "Sacramento International", city: "Sacramento", state: "CA", country: "US" },
  { code: "DAL", name: "Dallas Love Field", city: "Dallas Love Field", state: "TX", country: "US" },
  // ── US Medium & Small Hubs ─────────────────────────────────────────────────
  { code: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque", state: "NM", country: "US" },
  { code: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", state: "AK", country: "US" },
  { code: "ALB", name: "Albany International", city: "Albany", state: "NY", country: "US" },
  { code: "AMA", name: "Rick Husband Amarillo International", city: "Amarillo", state: "TX", country: "US" },
  { code: "ASE", name: "Aspen/Pitkin County Airport", city: "Aspen", state: "CO", country: "US" },
  { code: "AVL", name: "Asheville Regional Airport", city: "Asheville", state: "NC", country: "US" },
  { code: "BDL", name: "Bradley International", city: "Hartford/Springfield", state: "CT", country: "US" },
  { code: "BHM", name: "Birmingham-Shuttlesworth International", city: "Birmingham", state: "AL", country: "US" },
  { code: "BIL", name: "Billings Logan International", city: "Billings", state: "MT", country: "US" },
  { code: "BOI", name: "Boise Airport", city: "Boise", state: "ID", country: "US" },
  { code: "BTR", name: "Baton Rouge Metropolitan Airport", city: "Baton Rouge", state: "LA", country: "US" },
  { code: "BTV", name: "Burlington International", city: "Burlington", state: "VT", country: "US" },
  { code: "BUF", name: "Buffalo Niagara International", city: "Buffalo", state: "NY", country: "US" },
  { code: "BUR", name: "Hollywood Burbank Airport", city: "Burbank", state: "CA", country: "US" },
  { code: "BZN", name: "Bozeman Yellowstone International", city: "Bozeman", state: "MT", country: "US" },
  { code: "CAE", name: "Columbia Metropolitan Airport", city: "Columbia", state: "SC", country: "US" },
  { code: "CAK", name: "Akron-Canton Airport", city: "Akron", state: "OH", country: "US" },
  { code: "CHA", name: "Chattanooga Metropolitan Airport", city: "Chattanooga", state: "TN", country: "US" },
  { code: "CHS", name: "Charleston International", city: "Charleston", state: "SC", country: "US" },
  { code: "CID", name: "The Eastern Iowa Airport", city: "Cedar Rapids", state: "IA", country: "US" },
  { code: "CLE", name: "Cleveland Hopkins International", city: "Cleveland", state: "OH", country: "US" },
  { code: "CMH", name: "John Glenn Columbus International", city: "Columbus", state: "OH", country: "US" },
  { code: "COS", name: "Colorado Springs Airport", city: "Colorado Springs", state: "CO", country: "US" },
  { code: "CRP", name: "Corpus Christi International", city: "Corpus Christi", state: "TX", country: "US" },
  { code: "CVG", name: "Cincinnati/Northern Kentucky International", city: "Cincinnati", state: "KY", country: "US" },
  { code: "DAY", name: "Dayton International", city: "Dayton", state: "OH", country: "US" },
  { code: "DLH", name: "Duluth International Airport", city: "Duluth", state: "MN", country: "US" },
  { code: "DRO", name: "Durango-La Plata County Airport", city: "Durango", state: "CO", country: "US" },
  { code: "DSM", name: "Des Moines International", city: "Des Moines", state: "IA", country: "US" },
  { code: "EGE", name: "Eagle County Regional Airport", city: "Vail/Eagle", state: "CO", country: "US" },
  { code: "ELP", name: "El Paso International", city: "El Paso", state: "TX", country: "US" },
  { code: "EVV", name: "Evansville Regional Airport", city: "Evansville", state: "IN", country: "US" },
  { code: "EYW", name: "Key West International", city: "Key West", state: "FL", country: "US" },
  { code: "FAI", name: "Fairbanks International", city: "Fairbanks", state: "AK", country: "US" },
  { code: "FAR", name: "Hector International Airport", city: "Fargo", state: "ND", country: "US" },
  { code: "FAT", name: "Fresno Yosemite International", city: "Fresno", state: "CA", country: "US" },
  { code: "FAY", name: "Fayetteville Regional Airport", city: "Fayetteville", state: "NC", country: "US" },
  { code: "FCA", name: "Glacier Park International", city: "Kalispell", state: "MT", country: "US" },
  { code: "FLL", name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", state: "FL", country: "US" },
  { code: "FNT", name: "Bishop International Airport", city: "Flint", state: "MI", country: "US" },
  { code: "FSD", name: "Sioux Falls Regional Airport", city: "Sioux Falls", state: "SD", country: "US" },
  { code: "FWA", name: "Fort Wayne International Airport", city: "Fort Wayne", state: "IN", country: "US" },
  { code: "GEG", name: "Spokane International", city: "Spokane", state: "WA", country: "US" },
  { code: "GJT", name: "Grand Junction Regional Airport", city: "Grand Junction", state: "CO", country: "US" },
  { code: "GPT", name: "Gulfport-Biloxi International", city: "Gulfport", state: "MS", country: "US" },
  { code: "GRB", name: "Green Bay Austin Straubel International", city: "Green Bay", state: "WI", country: "US" },
  { code: "GRR", name: "Gerald R. Ford International", city: "Grand Rapids", state: "MI", country: "US" },
  { code: "GSO", name: "Piedmont Triad International", city: "Greensboro", state: "NC", country: "US" },
  { code: "GSP", name: "Greenville-Spartanburg International", city: "Greenville", state: "SC", country: "US" },
  { code: "GTF", name: "Great Falls International", city: "Great Falls", state: "MT", country: "US" },
  { code: "HDN", name: "Yampa Valley Regional Airport", city: "Steamboat Springs", state: "CO", country: "US" },
  { code: "HLN", name: "Helena Regional Airport", city: "Helena", state: "MT", country: "US" },
  { code: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", state: "HI", country: "US" },
  { code: "HPN", name: "Westchester County Airport", city: "White Plains", state: "NY", country: "US" },
  { code: "HRL", name: "Valley International Airport", city: "Harlingen", state: "TX", country: "US" },
  { code: "ICT", name: "Wichita Dwight D. Eisenhower National", city: "Wichita", state: "KS", country: "US" },
  { code: "IDA", name: "Idaho Falls Regional Airport", city: "Idaho Falls", state: "ID", country: "US" },
  { code: "ILM", name: "Wilmington International Airport", city: "Wilmington", state: "NC", country: "US" },
  { code: "IND", name: "Indianapolis International", city: "Indianapolis", state: "IN", country: "US" },
  { code: "ISP", name: "Long Island MacArthur Airport", city: "Islip", state: "NY", country: "US" },
  { code: "ITH", name: "Ithaca Tompkins International", city: "Ithaca", state: "NY", country: "US" },
  { code: "JAC", name: "Jackson Hole Airport", city: "Jackson Hole", state: "WY", country: "US" },
  { code: "JAN", name: "Jackson-Medgar Wiley Evers International", city: "Jackson", state: "MS", country: "US" },
  { code: "JAX", name: "Jacksonville International", city: "Jacksonville", state: "FL", country: "US" },
  { code: "JNU", name: "Juneau International", city: "Juneau", state: "AK", country: "US" },
  { code: "KOA", name: "Ellison Onizuka Kona International", city: "Kona", state: "HI", country: "US" },
  { code: "KTN", name: "Ketchikan International", city: "Ketchikan", state: "AK", country: "US" },
  { code: "LBB", name: "Lubbock Preston Smith International", city: "Lubbock", state: "TX", country: "US" },
  { code: "LEX", name: "Blue Grass Airport", city: "Lexington", state: "KY", country: "US" },
  { code: "LFT", name: "Lafayette Regional Airport", city: "Lafayette", state: "LA", country: "US" },
  { code: "LGB", name: "Long Beach Airport", city: "Long Beach", state: "CA", country: "US" },
  { code: "LIH", name: "Lihue Airport", city: "Kauai", state: "HI", country: "US" },
  { code: "LIT", name: "Clinton National Airport", city: "Little Rock", state: "AR", country: "US" },
  { code: "LNK", name: "Lincoln Airport", city: "Lincoln", state: "NE", country: "US" },
  { code: "MAF", name: "Midland International Air and Space Port", city: "Midland", state: "TX", country: "US" },
  { code: "MBS", name: "MBS International Airport", city: "Saginaw", state: "MI", country: "US" },
  { code: "MEM", name: "Memphis International", city: "Memphis", state: "TN", country: "US" },
  { code: "MFE", name: "McAllen Miller International Airport", city: "McAllen", state: "TX", country: "US" },
  { code: "MFR", name: "Rogue Valley International-Medford", city: "Medford", state: "OR", country: "US" },
  { code: "MGM", name: "Montgomery Regional Airport", city: "Montgomery", state: "AL", country: "US" },
  { code: "MHT", name: "Manchester-Boston Regional", city: "Manchester", state: "NH", country: "US" },
  { code: "MKE", name: "Milwaukee Mitchell International", city: "Milwaukee", state: "WI", country: "US" },
  { code: "MLB", name: "Melbourne Orlando International", city: "Melbourne", state: "FL", country: "US" },
  { code: "MLI", name: "Quad City International Airport", city: "Moline", state: "IL", country: "US" },
  { code: "MLU", name: "Monroe Regional Airport", city: "Monroe", state: "LA", country: "US" },
  { code: "MOB", name: "Mobile Regional Airport", city: "Mobile", state: "AL", country: "US" },
  { code: "MOT", name: "Minot International Airport", city: "Minot", state: "ND", country: "US" },
  { code: "MRY", name: "Monterey Regional Airport", city: "Monterey", state: "CA", country: "US" },
  { code: "MSN", name: "Dane County Regional Airport", city: "Madison", state: "WI", country: "US" },
  { code: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans", state: "LA", country: "US" },
  { code: "MTJ", name: "Montrose Regional Airport", city: "Montrose", state: "CO", country: "US" },
  { code: "MYR", name: "Myrtle Beach International", city: "Myrtle Beach", state: "SC", country: "US" },
  { code: "OGG", name: "Kahului Airport", city: "Maui", state: "HI", country: "US" },
  { code: "OKC", name: "Will Rogers World Airport", city: "Oklahoma City", state: "OK", country: "US" },
  { code: "OMA", name: "Eppley Airfield", city: "Omaha", state: "NE", country: "US" },
  { code: "ONT", name: "Ontario International", city: "Ontario", state: "CA", country: "US" },
  { code: "ORF", name: "Norfolk International", city: "Norfolk", state: "VA", country: "US" },
  { code: "PBI", name: "Palm Beach International", city: "West Palm Beach", state: "FL", country: "US" },
  { code: "PIT", name: "Pittsburgh International", city: "Pittsburgh", state: "PA", country: "US" },
  { code: "PSC", name: "Tri-Cities Airport", city: "Pasco", state: "WA", country: "US" },
  { code: "PSP", name: "Palm Springs International", city: "Palm Springs", state: "CA", country: "US" },
  { code: "PVD", name: "T.F. Green International", city: "Providence", state: "RI", country: "US" },
  { code: "RAP", name: "Rapid City Regional Airport", city: "Rapid City", state: "SD", country: "US" },
  { code: "RIC", name: "Richmond International", city: "Richmond", state: "VA", country: "US" },
  { code: "RNO", name: "Reno-Tahoe International", city: "Reno", state: "NV", country: "US" },
  { code: "ROA", name: "Roanoke-Blacksburg Regional", city: "Roanoke", state: "VA", country: "US" },
  { code: "ROC", name: "Greater Rochester International", city: "Rochester", state: "NY", country: "US" },
  { code: "RST", name: "Rochester International Airport", city: "Rochester", state: "MN", country: "US" },
  { code: "RSW", name: "Southwest Florida International", city: "Fort Myers", state: "FL", country: "US" },
  { code: "SAT", name: "San Antonio International", city: "San Antonio", state: "TX", country: "US" },
  { code: "SAV", name: "Savannah/Hilton Head International", city: "Savannah", state: "GA", country: "US" },
  { code: "SBA", name: "Santa Barbara Airport", city: "Santa Barbara", state: "CA", country: "US" },
  { code: "SBN", name: "South Bend International Airport", city: "South Bend", state: "IN", country: "US" },
  { code: "SDF", name: "Louisville Muhammad Ali International", city: "Louisville", state: "KY", country: "US" },
  { code: "SHV", name: "Shreveport Regional Airport", city: "Shreveport", state: "LA", country: "US" },
  { code: "SJU", name: "Luis Munoz Marin International", city: "San Juan", state: "PR", country: "US" },
  { code: "SNA", name: "John Wayne Airport", city: "Orange County", state: "CA", country: "US" },
  { code: "SRQ", name: "Sarasota Bradenton International", city: "Sarasota", state: "FL", country: "US" },
  { code: "SUN", name: "Friedman Memorial Airport", city: "Sun Valley", state: "ID", country: "US" },
  { code: "SYR", name: "Syracuse Hancock International", city: "Syracuse", state: "NY", country: "US" },
  { code: "TLH", name: "Tallahassee International Airport", city: "Tallahassee", state: "FL", country: "US" },
  { code: "TUL", name: "Tulsa International", city: "Tulsa", state: "OK", country: "US" },
  { code: "TUS", name: "Tucson International", city: "Tucson", state: "AZ", country: "US" },
  { code: "TVC", name: "Cherry Capital Airport", city: "Traverse City", state: "MI", country: "US" },
  { code: "TYS", name: "McGhee Tyson Airport", city: "Knoxville", state: "TN", country: "US" },
  { code: "XNA", name: "Northwest Arkansas National Airport", city: "Fayetteville", state: "AR", country: "US" },
  { code: "YAK", name: "Yakutat Airport", city: "Yakutat", state: "AK", country: "US" },
  { code: "YKM", name: "Yakima Air Terminal", city: "Yakima", state: "WA", country: "US" },
  // ── Alaska Regional ────────────────────────────────────────────────────────
  { code: "BET", name: "Bethel Airport", city: "Bethel", state: "AK", country: "US" },
  { code: "ADQ", name: "Kodiak Airport", city: "Kodiak", state: "AK", country: "US" },
  { code: "OME", name: "Nome Airport", city: "Nome", state: "AK", country: "US" },
  { code: "OTZ", name: "Ralph Wien Memorial Airport", city: "Kotzebue", state: "AK", country: "US" },
  { code: "SIT", name: "Sitka Rocky Gutierrez Airport", city: "Sitka", state: "AK", country: "US" },
  // ── Hawaii ─────────────────────────────────────────────────────────────────
  { code: "ITO", name: "Hilo International Airport", city: "Hilo", state: "HI", country: "US" },
  { code: "LNY", name: "Lanai Airport", city: "Lanai", state: "HI", country: "US" },
  // ── Canada ─────────────────────────────────────────────────────────────────
  { code: "YYZ", name: "Toronto Pearson International", city: "Toronto", state: "ON", country: "CA" },
  { code: "YVR", name: "Vancouver International", city: "Vancouver", state: "BC", country: "CA" },
  { code: "YUL", name: "Montreal-Trudeau International", city: "Montreal", state: "QC", country: "CA" },
  { code: "YYC", name: "Calgary International", city: "Calgary", state: "AB", country: "CA" },
  { code: "YEG", name: "Edmonton International", city: "Edmonton", state: "AB", country: "CA" },
  { code: "YOW", name: "Ottawa Macdonald-Cartier International", city: "Ottawa", state: "ON", country: "CA" },
  { code: "YHZ", name: "Halifax Stanfield International", city: "Halifax", state: "NS", country: "CA" },
  { code: "YWG", name: "Winnipeg James Armstrong Richardson International", city: "Winnipeg", state: "MB", country: "CA" },
  // ── Europe ─────────────────────────────────────────────────────────────────
  { code: "LHR", name: "Heathrow Airport", city: "London", state: "", country: "GB" },
  { code: "LGW", name: "Gatwick Airport", city: "London Gatwick", state: "", country: "GB" },
  { code: "STN", name: "Stansted Airport", city: "London Stansted", state: "", country: "GB" },
  { code: "CDG", name: "Charles de Gaulle Airport", city: "Paris", state: "", country: "FR" },
  { code: "ORY", name: "Paris Orly Airport", city: "Paris Orly", state: "", country: "FR" },
  { code: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam", state: "", country: "NL" },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", state: "", country: "DE" },
  { code: "MUC", name: "Munich Airport", city: "Munich", state: "", country: "DE" },
  { code: "MAD", name: "Adolfo Suarez Madrid-Barajas", city: "Madrid", state: "", country: "ES" },
  { code: "BCN", name: "El Prat Airport", city: "Barcelona", state: "", country: "ES" },
  { code: "FCO", name: "Fiumicino Airport", city: "Rome", state: "", country: "IT" },
  { code: "MXP", name: "Milan Malpensa Airport", city: "Milan", state: "", country: "IT" },
  { code: "ZRH", name: "Zurich Airport", city: "Zurich", state: "", country: "CH" },
  { code: "VIE", name: "Vienna International Airport", city: "Vienna", state: "", country: "AT" },
  { code: "BRU", name: "Brussels Airport", city: "Brussels", state: "", country: "BE" },
  { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen", state: "", country: "DK" },
  { code: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", state: "", country: "SE" },
  { code: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki", state: "", country: "FI" },
  { code: "OSL", name: "Oslo Gardermoen Airport", city: "Oslo", state: "", country: "NO" },
  { code: "DUB", name: "Dublin Airport", city: "Dublin", state: "", country: "IE" },
  { code: "LIS", name: "Lisbon Humberto Delgado Airport", city: "Lisbon", state: "", country: "PT" },
  { code: "ATH", name: "Athens Eleftherios Venizelos International", city: "Athens", state: "", country: "GR" },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul", state: "", country: "TR" },
  { code: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", state: "", country: "PL" },
  { code: "PRG", name: "Vaclav Havel Airport Prague", city: "Prague", state: "", country: "CZ" },
  { code: "BUD", name: "Budapest Ferenc Liszt International", city: "Budapest", state: "", country: "HU" },
  // ── Asia-Pacific ───────────────────────────────────────────────────────────
  { code: "NRT", name: "Narita International Airport", city: "Tokyo", state: "", country: "JP" },
  { code: "HND", name: "Tokyo Haneda Airport", city: "Tokyo Haneda", state: "", country: "JP" },
  { code: "KIX", name: "Kansai International Airport", city: "Osaka", state: "", country: "JP" },
  { code: "ICN", name: "Incheon International Airport", city: "Seoul", state: "", country: "KR" },
  { code: "PEK", name: "Beijing Capital International", city: "Beijing", state: "", country: "CN" },
  { code: "PVG", name: "Shanghai Pudong International", city: "Shanghai", state: "", country: "CN" },
  { code: "HKG", name: "Hong Kong International", city: "Hong Kong", state: "", country: "HK" },
  { code: "SIN", name: "Singapore Changi Airport", city: "Singapore", state: "", country: "SG" },
  { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", state: "", country: "TH" },
  { code: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", state: "", country: "MY" },
  { code: "CGK", name: "Soekarno-Hatta International", city: "Jakarta", state: "", country: "ID" },
  { code: "MNL", name: "Ninoy Aquino International", city: "Manila", state: "", country: "PH" },
  { code: "DEL", name: "Indira Gandhi International", city: "New Delhi", state: "", country: "IN" },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", state: "", country: "IN" },
  { code: "BLR", name: "Kempegowda International", city: "Bengaluru", state: "", country: "IN" },
  { code: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", state: "", country: "AU" },
  { code: "MEL", name: "Melbourne Airport", city: "Melbourne", state: "", country: "AU" },
  { code: "BNE", name: "Brisbane Airport", city: "Brisbane", state: "", country: "AU" },
  { code: "AKL", name: "Auckland Airport", city: "Auckland", state: "", country: "NZ" },
  // ── Middle East & Africa ───────────────────────────────────────────────────
  { code: "DXB", name: "Dubai International Airport", city: "Dubai", state: "", country: "AE" },
  { code: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi", state: "", country: "AE" },
  { code: "DOH", name: "Hamad International Airport", city: "Doha", state: "", country: "QA" },
  { code: "RUH", name: "King Khalid International", city: "Riyadh", state: "", country: "SA" },
  { code: "CAI", name: "Cairo International Airport", city: "Cairo", state: "", country: "EG" },
  { code: "JNB", name: "O.R. Tambo International", city: "Johannesburg", state: "", country: "ZA" },
  { code: "CPT", name: "Cape Town International", city: "Cape Town", state: "", country: "ZA" },
  { code: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", state: "", country: "KE" },
  { code: "LOS", name: "Murtala Muhammed International", city: "Lagos", state: "", country: "NG" },
  { code: "ADD", name: "Bole International Airport", city: "Addis Ababa", state: "", country: "ET" },
  // ── Latin America & Caribbean ──────────────────────────────────────────────
  { code: "MEX", name: "Benito Juarez International", city: "Mexico City", state: "", country: "MX" },
  { code: "CUN", name: "Cancun International", city: "Cancun", state: "", country: "MX" },
  { code: "GDL", name: "Don Miguel Hidalgo y Costilla International", city: "Guadalajara", state: "", country: "MX" },
  { code: "GRU", name: "Guarulhos International", city: "Sao Paulo", state: "", country: "BR" },
  { code: "GIG", name: "Galeao International", city: "Rio de Janeiro", state: "", country: "BR" },
  { code: "EZE", name: "Ministro Pistarini International", city: "Buenos Aires", state: "", country: "AR" },
  { code: "SCL", name: "Arturo Merino Benitez International", city: "Santiago", state: "", country: "CL" },
  { code: "LIM", name: "Jorge Chavez International", city: "Lima", state: "", country: "PE" },
  { code: "BOG", name: "El Dorado International", city: "Bogota", state: "", country: "CO" },
  { code: "NAS", name: "Lynden Pindling International", city: "Nassau", state: "", country: "BS" },
  { code: "MBJ", name: "Sangster International", city: "Montego Bay", state: "", country: "JM" },
  { code: "SJU", name: "Luis Munoz Marin International", city: "San Juan", state: "PR", country: "US" },
  { code: "STT", name: "Cyril E. King Airport", city: "St. Thomas", state: "VI", country: "US" },
  { code: "PUJ", name: "Punta Cana International", city: "Punta Cana", state: "", country: "DO" },
  { code: "HAV", name: "Jose Marti International", city: "Havana", state: "", country: "CU" },
];

export function airportLabel(a) {
  if (!a) return '';
  const loc = a.state ? `${a.city}, ${a.state}` : `${a.city}, ${a.country}`;
  return `${a.code} — ${loc}`;
}
